apiVersion: apps/v1beta2 # before 1.9
kind: Deployment
metadata:
  name: chat-ui
spec:
  selector:
    matchLabels:
      app: chat-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: chat-ui
    spec:
      containers:
      - name: chat-ui
        image: pineappleworkshop/chat-ui:0.0.11
